"""Render the agent-facing AGENT_ACCESS.txt.

This file is mounted ro inside the container at /workspace/.botainer/AGENT_ACCESS.txt
and is the only "what can I do" reference the agent reads at session start.

Per codex MEDIUM 8: wording is "reduces accidental instruction confusion in
the agent-facing rendering"; we still sanitize plugin-supplied strings.
"""

from __future__ import annotations

from botainer.core.spec import SessionSpec

_MAX_PLUGIN_STRING_LEN = 120
_DELIM_OPEN = "«"
_DELIM_CLOSE = "»"


def _sanitize(s: str) -> str:
    """Trim plugin-supplied strings; replace control chars with spaces."""
    if not s:
        return ""
    out = []
    for ch in s[:_MAX_PLUGIN_STRING_LEN]:
        out.append(ch if ch.isprintable() else " ")
    return "".join(out)


def render(spec: SessionSpec) -> str:
    lines = []
    lines.append("# AGENT_ACCESS — what you (the agent) can do in this session.")
    lines.append(
        "# Generated by botainer. Read-only. The user can see this same view via `botainer access`."
    )
    lines.append("")
    lines.append(f"session_id: {spec.session_id}")
    lines.append(f"project:    {spec.project_root}")
    lines.append(f"profile:    {spec.profile}")
    lines.append("")
    lines.append("## What you can reach")
    lines.append("")
    lines.append("network:")
    lines.append(f"  mode: {spec.network.mode.value}")
    if spec.network.endpoints:
        lines.append("  endpoints (requested allowlist — NOT enforced at v0.1):")
        for e in spec.network.endpoints:
            lines.append(f"    - {e}")
    # #175: host_services config field was retired. The intended use
    # case (agent reaches a named host service) is now served by
    # BindMode.UNIX_SOCKET binds (see plugins/wolfram-sidecar).
    lines.append("")
    lines.append("filesystem (bind mounts inside this container):")
    for b in spec.mount_plan.binds:
        if b.agent_rendering.value == "summarized":
            continue
        marker = b.mode.value
        detail = _sanitize(b.provenance_detail)
        lines.append(f"  {b.target} ({marker})  {_DELIM_OPEN}{detail}{_DELIM_CLOSE}")
    lines.append("")
    # Tasks #95/#291: contributes.sidecars is refused fail-closed at
    # compose time (composition.py), so spec.sidecars is empty in any
    # valid in-tree compose. Renderer kept as a defense-in-depth surface
    # in case a test or fuzzer constructs a SessionSpec directly with
    # non-empty sidecars; labels them as NOT RUNNING.
    if spec.sidecars:
        lines.append("sidecars (DECLARED but NOT launched in v0.1.0; see #95):")
        for s in spec.sidecars:
            lines.append(f"  - {s.name} via {_DELIM_OPEN}{_sanitize(s.image or '')}{_DELIM_CLOSE}  (NOT RUNNING)")
        lines.append("")
    lines.append("## What you can NOT do")
    lines.append("- write outside /workspace (no other writable paths unless explicitly bound rw)")
    lines.append("- reach the host filesystem beyond the binds listed above (those are your host-visible paths for this session)")
    lines.append("- launch sibling containers (no docker socket bound)")
    lines.append("- modify your own AGENT_ACCESS.txt (mounted ro)")
    lines.append("")
    lines.append("## Reminder")
    lines.append("Anything you do in /workspace can affect the project on the user's host")
    lines.append("checkout. The user has been told to treat this checkout as untrusted")
    lines.append("after your session.")
    return "\n".join(lines) + "\n"
